import type { Metadata } from "next";
import { ConvexClientProvider } from "@/providers/ConvexClientProvider";
import "@liveblocks/react-ui/styles.css";
import "@liveblocks/react-tiptap/styles.css";
import "@/styles/globals.css";

export const metadata: Metadata = {
	title: "Google Docs Clone",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link rel="icon" type="image/svg+xml" href="/logo.svg" />
			</head>
			<body className={`antialiased`}>
				<ConvexClientProvider>{children}</ConvexClientProvider>
			</body>
		</html>
	);
}
